name: drew.little
description: forecast
version: 0.0.1
author: cb55fvfb.sv9ctw3f@5qz627j4.com
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines:
  pipelines/Evelin_HammesSherman_Wadd_EvverAlphonso_Hegmann:
    name: Evelin_HammesSherman_Wadd_EvverAlphonso_Hegmann
    description: null
    author: cb55fvfb.sv9ctw3f@5qz627j4.com
    mode: batch
    artefactID: ''
    language: sql
    createdAt: '2025-07-04 21:06:58'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/Renee_PredovicChris_P__WheatzenraisinsDenny_Greenfelder:
    name: Renee_PredovicChris_P__WheatzenraisinsDenny_Greenfelder
    description: null
    author: cb55fvfb.sv9ctw3f@5qz627j4.com
    mode: batch
    artefactID: ''
    language: sql
    createdAt: '2025-07-04 21:06:59'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-07-04 21:06:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: cb55fvfb.sv9ctw3f@5qz627j4.com
  createdAt: '2025-07-04 21:06:57'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
